In [1]:
# ============================================
# FIND-S ALGORITHM
# Read CSV file uploaded by the user
# ============================================

import pandas as pd
from google.colab import files

print("Upload your CSV file:")

uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

# Read CSV
data = pd.read_csv(filename)

print("\nDataset loaded successfully!")
print("Filename:", filename)
print("Shape:", data.shape)

print("\nFirst 5 rows:")
print(data.head())

Upload your CSV file:

Saving archive.zip to archive.zip

Dataset loaded successfully!
Filename: archive.zip
Shape: (14, 6)

First 5 rows:
  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [2]:
# ============================================
# CHECK DATASET
# ============================================

print("\nColumn names:")
print(data.columns.tolist())

print("\nDataset:")
print(data)

print("\nDataset information:")
print(data.info())

Column names:
['day', 'outlook', 'temp', 'humidity', 'wind', 'play']

Dataset:
    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   day       14 non-null     object
 1   outlook   14 non-null     object
 2   temp      14 non-null     object
 3   humidity  14 non-null     object
 4   wind      14 non-null     object
 5   play      14 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes
None

In [3]:
# ============================================
# IDENTIFY TARGET COLUMN
# ============================================

print("\nAvailable columns:")
for i, column in enumerate(data.columns):
    print(i, ":", column)

target = data.columns[-1]

print("\nTarget column selected:", target)

Available columns:
0 : day
1 : outlook
2 : temp
3 : humidity
4 : wind
5 : play

Target column selected: play

In [4]:
# ============================================
# IDENTIFY TARGET COLUMN
# ============================================

print("\nAvailable columns:")
for i, column in enumerate(data.columns):
    print(i, ":", column)

target = data.columns[-1]

print("\nTarget column selected:", target)

Available columns:
0 : day
1 : outlook
2 : temp
3 : humidity
4 : wind
5 : play

Target column selected: play

In [5]:
# ============================================
# DATA PREPROCESSING
# ============================================

# Remove Day if it exists
if "Day" in data.columns:
    data = data.drop("Day", axis=1)

# Remove rows containing missing values
data = data.dropna()

print("\nDataset after preprocessing:")
print(data)

print("\nNumber of rows:", len(data))

Dataset after preprocessing:
    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

Number of rows: 14

In [6]:
# ============================================
# FIND-S ALGORITHM
# ============================================

# Get attribute columns
attributes = list(data.columns)

# Remove target column
attributes.remove(target)

print("\nAttributes:")
print(attributes)

# Start with most specific hypothesis
hypothesis = ["∅"] * len(attributes)

print("\nInitial Hypothesis:")
print(hypothesis)


# ============================================
# PROCESS TRAINING EXAMPLES
# ============================================

for index, row in data.iterrows():

    # Process only positive examples
    if str(row[target]).strip().lower() == "yes":

        print("\n----------------------------------------")
        print("Positive Example:", index + 1)
        print("----------------------------------------")

        for i in range(len(attributes)):

            # First positive example
            if hypothesis[i] == "∅":
                hypothesis[i] = row[attributes[i]]

            # If values are different,
            # generalize the hypothesis
            elif hypothesis[i] != row[attributes[i]]:
                hypothesis[i] = "?"

        print("Current Hypothesis:")
        print(hypothesis)

Attributes:
['day', 'outlook', 'temp', 'humidity', 'wind']

Initial Hypothesis:
['∅', '∅', '∅', '∅', '∅']

----------------------------------------
Positive Example: 3
----------------------------------------
Current Hypothesis:
['D3', 'Overcast', 'Hot', 'High', 'Weak']

----------------------------------------
Positive Example: 4
----------------------------------------
Current Hypothesis:
['?', '?', '?', 'High', 'Weak']

----------------------------------------
Positive Example: 5
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', 'Weak']

----------------------------------------
Positive Example: 7
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', '?']

----------------------------------------
Positive Example: 9
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', '?']

----------------------------------------
Positive Example: 10
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', '?']

----------------------------------------
Positive Example: 11
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', '?']

----------------------------------------
Positive Example: 12
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', '?']

----------------------------------------
Positive Example: 13
----------------------------------------
Current Hypothesis:
['?', '?', '?', '?', '?']

In [14]:
# ============================================
# FINAL HYPOTHESIS
# ============================================

print("\n============================================")
print("FINAL HYPOTHESIS")
print("============================================")

for attribute, value in zip(attributes, hypothesis):
    print(attribute, "=", value)

print("\nMost Specific Hypothesis:")
print(hypothesis)

============================================
FINAL HYPOTHESIS
============================================
day = ?
outlook = ?
temp = ?
humidity = ?
wind = ?

Most Specific Hypothesis:
['?', '?', '?', '?', '?']

In [9]:
import pandas as pd
import random

random.seed(42)

outlook = ["Sunny", "Overcast", "Rain"]
temp = ["Hot", "Mild", "Cool"]
humidity = ["High", "Normal"]
wind = ["Weak", "Strong"]

data = []

for i in range(100):
    o = random.choice(outlook)
    t = random.choice(temp)
    h = random.choice(humidity)
    w = random.choice(wind)

    # Simple realistic rule for Play Tennis
    if o == "Overcast":
        play = "Yes"
    elif o == "Sunny" and h == "High":
        play = "No"
    elif o == "Rain" and w == "Strong":
        play = "No"
    else:
        play = "Yes"

    data.append([o, t, h, w, play])

df = pd.DataFrame(
    data,
    columns=["outlook", "temp", "humidity", "wind", "play"]
)

print("Dataset created successfully!")
print("Shape:", df.shape)

df.head(10)

Dataset created successfully!
Shape: (100, 5)

    outlook  temp humidity    wind play
0      Rain   Hot     High  Strong   No
1     Sunny   Hot     High    Weak   No
2      Rain  Cool     High  Strong   No
3     Sunny   Hot     High    Weak   No
4     Sunny  Cool     High    Weak   No
5      Rain  Cool   Normal    Weak  Yes
6  Overcast  Cool   Normal    Weak  Yes
7     Sunny  Cool   Normal  Strong  Yes
8  Overcast   Hot     High  Strong  Yes
9     Sunny   Hot   Normal    Weak  Yes

In [10]:
print("Number of rows:", len(df))
print("\nColumns:")
print(df.columns.tolist())

print("\nPlay distribution:")
print(df["play"].value_counts())

print("\nComplete dataset:")
display(df)

Number of rows: 100

Columns:
['outlook', 'temp', 'humidity', 'wind', 'play']

Play distribution:
play
Yes    65
No     35
Name: count, dtype: int64

Complete dataset:

   outlook  temp humidity    wind play
0     Rain   Hot     High  Strong   No
1    Sunny   Hot     High    Weak   No
2     Rain  Cool     High  Strong   No
3    Sunny   Hot     High    Weak   No
4    Sunny  Cool     High    Weak   No
..     ...   ...      ...     ...  ...
95    Rain  Cool     High    Weak  Yes
96   Sunny   Hot   Normal    Weak  Yes
97   Sunny  Cool   Normal  Strong  Yes
98    Rain  Cool     High  Strong   No
99   Sunny  Cool     High  Strong   No

[100 rows x 5 columns]

In [11]:
df.to_csv("find_s_large_dataset.csv", index=False)

print("CSV file saved successfully!")

CSV file saved successfully!

In [12]:
from google.colab import files

files.download("find_s_large_dataset.csv")